### ISSUE TITLE
Licencing

### ISSUE THREAD

**Issue by VoyTechnology** [SaferPlace/frontend#20]
This issue would probably apply to all other repositories in the org. The original [CianLR/coireacht](https://github.com/CianLR/coireacht) is licenced under MIT licence. However, this project is a replica of the old project, and it shares no actual code.

I am asking the original authors @iandioch and @CianLR, what LICENCE do you see fit? I have no preference.

**Comment by iandioch** [comment]
It's in the spirit of the MIT licence for copies of the work to have the licence, as well as descendants. Regardless, it is a good general purpose open licence. That'd be my vote.
